import { WidgetType, ChartType } from './types.js';

export const DEFAULT_WIDGETS = [
  {
    id: 'total-sales',
    type: WidgetType.Metric,
    title: 'Total Sales',
    value: '462,897',
    unit: 'USD',
    trend: '+20.1%',
    trendDirection: 'up',
  },
  {
    id: 'subscriptions',
    type: WidgetType.Metric,
    title: 'Subscriptions',
    value: '2,350',
    trend: '+12.5%',
    trendDirection: 'up',
  },
  {
    id: 'open-tickets',
    type: WidgetType.Metric,
    title: 'Open Tickets',
    value: '18',
    trend: '-5.2%',
    trendDirection: 'down',
  },
  {
    id: 'customer-satisfaction',
    type: WidgetType.Metric,
    title: 'Customer Satisfaction',
    value: '92.7%',
    trend: '+0.5%',
    trendDirection: 'up',
  },
  {
    id: 'sales-by-month',
    type: WidgetType.Chart,
    chartType: ChartType.Bar,
    title: 'Sales by Month',
    dataKey: 'sales',
    nameKey: 'month',
    data: [
      { month: 'Jan', sales: 4000 },
      { month: 'Feb', sales: 3000 },
      { month: 'Mar', sales: 5000 },
      { month: 'Apr', sales: 4500 },
      { month: 'May', sales: 6000 },
      { month: 'Jun', sales: 5500 },
    ],
  },
  {
    id: 'user-signups',
    type: WidgetType.Chart,
    chartType: ChartType.Area,
    title: 'User Signups (Last 7 Days)',
    dataKey: 'signups',
    nameKey: 'day',
    data: [
        { day: 'Mon', signups: 120 },
        { day: 'Tue', signups: 200 },
        { day: 'Wed', signups: 150 },
        { day: 'Thu', signups: 280 },
        { day: 'Fri', signups: 210 },
        { day: 'Sat', signups: 350 },
        { day: 'Sun', signups: 300 },
    ],
  },
  {
    id: 'device-usage',
    type: WidgetType.Chart,
    chartType: ChartType.Pie,
    title: 'Device Usage',
    dataKey: 'value',
    nameKey: 'name',
    data: [
        { name: 'Desktop', value: 45 },
        { name: 'Mobile', value: 35 },
        { name: 'Tablet', value: 20 },
    ],
  },
];

export const DEFAULT_LAYOUTS = {
  lg: [
    { i: 'total-sales', x: 0, y: 0, w: 1, h: 1 },
    { i: 'subscriptions', x: 1, y: 0, w: 1, h: 1 },
    { i: 'open-tickets', x: 2, y: 0, w: 1, h: 1 },
    { i: 'customer-satisfaction', x: 3, y: 0, w: 1, h: 1 },
    { i: 'sales-by-month', x: 0, y: 1, w: 2, h: 2 },
    { i: 'user-signups', x: 2, y: 1, w: 2, h: 2 },
    { i: 'device-usage', x: 0, y: 3, w: 2, h: 2 },
  ],
  md: [
    { i: 'total-sales', x: 0, y: 0, w: 1, h: 1 },
    { i: 'subscriptions', x: 1, y: 0, w: 1, h: 1 },
    { i: 'open-tickets', x: 0, y: 1, w: 1, h: 1 },
    { i: 'customer-satisfaction', x: 1, y: 1, w: 1, h: 1 },
    { i: 'sales-by-month', x: 0, y: 2, w: 2, h: 2 },
    { i: 'user-signups', x: 0, y: 4, w: 2, h: 2 },
    { i: 'device-usage', x: 0, y: 6, w: 2, h: 2 },
  ],
};